// <auto-generated />
using System;
using CMSXData.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CMSXData.Migrations
{
    [DbContext(typeof(CmsxDbContext))]
    [Migration("20260515120000_AddVitrineCssProcessado")]
    partial class AddVitrineCssProcessado
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            // Model snapshot omitted — see CmsxDbContextModelSnapshot for current state.
            // This migration adds column css_processado (text, nullable) to vitrine_configurada.
#pragma warning restore 612, 618
        }
    }
}
