// <auto-generated />
using CMSXData.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace CMSXData.Migrations
{
    [DbContext(typeof(CmsxDbContext))]
    [Migration("20260502000000_AddProdutoMaoDeObra")]
    partial class AddProdutoMaoDeObra
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
        }
    }
}
